name: Tests

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  tests:
    runs-on: ${{ matrix.operating-system }}
    # We want to run on external PRs, but not on our own internal PRs as they'll be run by the push to the branch.
    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository)

    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-20.04]
        php-versions: ['8.0', '8.1']
        beta: ['beta', '']
        dependencies: ['locked', 'lowest', 'highest']
        exclude:
          - beta: 'beta'
            dependencies: 'locked'
          - beta: 'beta'
            dependencies: 'lowest'

    name: PHP ${{ matrix.php-versions }} -- ${{ matrix.beta }} ${{ matrix.dependencies }}

    env:
      extensions: curl, dom, imagick, json, libxml, mbstring
      key: cache-v1 # can be any string, change to clear the extension cache.

    steps:
      # Checks out a copy of your repository on the ubuntu machine
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Up Imagick, FFmpeg & Exiftools
        run: |
          sudo apt-get update
          sudo apt-get --fix-broken install
          sudo apt-get -y install ffmpeg libimage-exiftool-perl libmagickwand-dev

      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.15.0
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.extensions }}
          coverage: xdebug
          tools: pecl, composer

      - name: Fix beta
        if: ${{ matrix.beta == 'beta' }}
        run: perl -pi -e 's/^}$/,"minimum-stability":"beta"}/' composer.json

      # Install dependencies and handle caching in one go.
      # Dependencies need to be installed to make sure the PHPUnit classes are recognized.
      # @link https://github.com/marketplace/actions/install-php-dependencies-with-composer
      - name: Install Composer dependencies
        uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: "${{ matrix.dependencies }}"

      # - name: boot test server
      #   run: vendor/bin/http_test_server > /dev/null 2>&1 &

      - name: Prepare log directory
        run: mkdir -p build/logs

      - name: Validate files
        run: composer validate-files

      - name: Check Style
        run: composer check-code-style

      - name: Run tests
        run: composer run-tests
