name: Tests

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  tests:
    runs-on: ${{ matrix.operating-system }}
    # We want to run on external PRs, but not on our own internal PRs as they'll be run by the push to the branch.
    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository)

    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-20.04]
        php-versions: ['8.0', '8.1']
        dependencies: ['no', 'low', 'beta']

    name: PHP ${{ matrix.php-versions }} - ${{ matrix.dependencies }}

    env:
      extensions: curl, dom, imagick, json, libxml, mbstring
      key: cache-v1 # can be any string, change to clear the extension cache.

    steps:
      # Checks out a copy of your repository on the ubuntu machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@1.6.2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.extensions }}
          key: ${{ env.key }}

      - name: Cache PHP Extensions
        uses: actions/cache@v2
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Cache Composer Dependencies
        uses: actions/cache@v2.1.6
        with:
          path: ~/.composer/cache/files
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.15.0
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.extensions }}
          coverage: xdebug
          tools: pecl, composer

      - name: Set Up Imagick, FFmpeg & Exiftools
        run: |
          sudo apt-get update
          sudo apt-get --fix-broken install
          sudo apt-get -y install ffmpeg libimage-exiftool-perl libmagickwand-dev

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Fix beta
        if: ${{ matrix.dependencies == 'beta' }}
        run: perl -pi -e 's/^}$/,"minimum-stability":"beta"}/' composer.json

      - name: Install Composer dependencies (normal)
        if: ${{ matrix.dependencies != 'low' }}
        run: composer update --no-interaction

      - name: Install Composer dependencies (low)
        if: ${{ matrix.dependencies == 'low' }}
        run: composer update -vvv --prefer-lowest --prefer-stable --no-interaction

      # - name: boot test server
      #   run: vendor/bin/http_test_server > /dev/null 2>&1 &

      - name: Prepare log directory
        run: mkdir -p build/logs

      - name: Validate files
        run: composer validate-files
      
      - name: Check Style
        run: composer check-code-style

      - name: Run tests
        run: composer run-tests
